### ISSUE TITLE
Нужно удалить мусор из репозитория

### ISSUE THREAD

**Issue by coursar** [ArkhipovMarat/WallpaperCount-calculator#3]
Сначала добавляйте .gitignore, потом уже инициализируйте git репозиторий

Сейчас в IDEA нужно:
1. Alt + F12
2. В консоли выполнить команды:
```
git rm --cached -r .idea
git rm --cached -r *.iml
```

После чего сделать коммит и пуш

**Comment by ArkhipovMarat** [comment]
@coursar исправил
